@startuml
!theme plain
skinparam linetype ortho

rectangle "Switch" as switch {
}

rectangle "ESP32 Module" as esp32 {
  [API Server] as api
}

rectangle "Crawler Service" as crawlerService {
}

rectangle "Homebridge Service" as homebridge {
  [Meross Plugin] as merossPlugin
}

rectangle "InfluxDB" as influxdb {
}

switch --> merossPlugin : Send raw logs<U+0020><U+0020><U+0020><U+0020><U+0020><U+0020><U+0020>
crawlerService <--> merossPlugin : Read and parse
api --> influxdb : Retrieve logs
crawlerService --> influxdb: Send parsed logs

@enduml
